-- شغّل هذا الملف مرة واحدة في Supabase SQL Editor.

create table if not exists public.ai_knowledge (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  keywords text,
  source_url text,
  category text default 'عام',
  sort_order integer default 0,
  is_active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists ai_knowledge_active_sort_idx
  on public.ai_knowledge (is_active, sort_order);

alter table public.ai_knowledge enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'ai_knowledge'
      and policyname = 'Authenticated admins can manage AI knowledge'
  ) then
    create policy "Authenticated admins can manage AI knowledge"
      on public.ai_knowledge
      for all
      to authenticated
      using (true)
      with check (true);
  end if;
end $$;

insert into public.ai_knowledge (title, content, keywords, source_url, category, sort_order, is_active)
select * from (values
  (
    'تعريف ملتقى الطالب الجامعي',
    'ملتقى الطالب الجامعي كيان طلابي يسعى إلى خدمة الطالب الجامعي، وتبني قضاياه، والدفاع عن حقوقه، وتنمية وعيه وقدراته عبر البرامج والأنشطة المتنوعة.',
    'تعريف الملتقى، من هو الملتقى، ملتقى الطالب الجامعي',
    'https://usf-flax.vercel.app/about',
    'عن الملتقى', 1, true
  ),
  (
    'طريقة الانضمام إلى الملتقى',
    'يمكن للطالب تقديم طلب الانضمام عبر صفحة الانضمام، ثم تعبئة البيانات الأساسية واختيار اللجنة المناسبة. بعد إرسال الطلب يتواصل الملتقى مع الطالب عبر رقم الهاتف المسجل.',
    'الانضمام، التسجيل، طلب عضوية، اللجان',
    'https://usf-flax.vercel.app/join',
    'الانضمام', 2, true
  ),
  (
    'شروط العضوية',
    'أن يكون المتقدم من طلاب جامعة العلوم والتكنولوجيا، حسن السيرة والسلوك، ملتزمًا بلوائح الملتقى، عاملًا للمصلحة العامة وخدمة الطلاب، ومستشعرًا للمسؤولية في العمل الموكل إليه.',
    'شروط الانضمام، شروط العضوية، طالب الجامعة',
    'https://usf-flax.vercel.app/join',
    'الانضمام', 3, true
  ),
  (
    'لجان ملتقى الطالب الجامعي',
    'تضم لجان الملتقى: اللجنة العلمية، لجنة المبادرات الطلابية، لجنة الأنشطة الطلابية، اللجنة الإعلامية الطلابية، اللجنة الثقافية الطلابية، لجنة شؤون الطلبة، ولجنة التدريب الطلابية. تظهر مهام وروابط كل لجنة في صفحة اللجان.',
    'اللجان، اللجنة العلمية، الإعلامية، الثقافية، الأنشطة، التدريب، شؤون الطلبة',
    'https://usf-flax.vercel.app/committees',
    'اللجان', 4, true
  ),
  (
    'خدمات الموقع',
    'يوفر موقع ملتقى الطالب الجامعي الأخبار والأنشطة والدورات واللجان والمبادرات والإنجازات والفعاليات، كما يتيح تقديم طلب الانضمام وإرسال الشكاوى والإشكاليات الطلابية.',
    'الخدمات، الأخبار، الأنشطة، الدورات، الشكاوى، المبادرات',
    'https://usf-flax.vercel.app/',
    'الخدمات', 5, true
  ),
  (
    'تقديم شكوى أو إشكالية',
    'يمكن للطالب إرسال شكوى أو إشكالية أو اقتراح من صفحة الشكاوى في الموقع، مع كتابة بيانات التواصل والعنوان والتفاصيل بوضوح لتصل إلى الجهة المختصة.',
    'شكوى، إشكالية، اقتراح، مشكلة طالب',
    'https://usf-flax.vercel.app/issues',
    'الخدمات', 6, true
  )
) as seed(title, content, keywords, source_url, category, sort_order, is_active)
where not exists (
  select 1 from public.ai_knowledge existing where existing.title = seed.title
);

comment on table public.ai_knowledge is
  'المعلومات المعتمدة التي يستخدمها مساعد ملتقى الطالب الجامعي الذكي.';
